config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"}

  resources :games, only: %i[index show] do
  	resources :entries, only: [:new, :create, :destroy]
  end

  namespace :admin do
    resources :games do
      member do
        post :create_number, path: :numbers
      end 
    end
  end

  match "*path" => "application#error_404", via: :all
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_one :card, dependent: :destroy
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_not_admin

  def new
    # 既に参加済み
    return redirect_to game_url(params[:game_id]) if current_user.registered_for_game?(params[:game_id])

    @game = Game.find(params[:game_id])
  end

  # ゲームに参加
  def create
    # 既に参加済み
    return redirect_to game_url(params[:game_id]) if current_user.registered_for_game?(params[:game_id])

    Entry.transaction do
      entry = current_user.entries.build(game_id: params[:game_id])
      entry.save!

      card = entry.build_card(numbers: Card.generate_numbers)
      card.save!
    end
    flash[:notice] = 'ゲームに参加しました。'
    redirect_to game_url(params[:game_id])
  end

  def destroy
    entry = current_user.entries.find_by!(game_id: params[:game_id])
    entry.destroy!
    redirect_to games_url, notice: 'ゲームの参加をキャンセルしました。'
  end

  private

  # 管理者はゲームに参加できない
  def confirm_not_admin
    return redirect_to root_url, notice: '管理者はゲームに参加できません。' if current_user.admin?
  end
end

app/views/entries/new.html.erb
<h1><%= @game.name =%></h1>

<div class="text-center"><%= @game.name =%>に参加しますか？</div>
<br>
<%= form_for(@game.entries.build, url: game_entries_path(@game)) do |form| %>
  <% if @entry && @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit '参加する', {class: 'btn btn-primary center-block', style: 'width: 200px;'} %>
  </div>
<% end %>
<br>
<%= link_to 'キャンセル', games_path, class: 'btn btn-link center-block' %>