config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"}

  resources :games, only: %i[index show] do
  	resources :entries, only: [:new, :create, :destroy]
  end

  namespace :admin do
    resources :games do
      member do
        post :create_number, path: :numbers
      end 
    end
  end

  match "*path" => "application#error_404", via: :all
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries

  validates :name, length: { maximum: 50 }, presence: true
  validates :start_time, presence: true

  validate :start_time_should_be_after_now, on: :create

  serialize :numbers, JSON

  def self.default_name
    'XXX ビンゴ大会'
  end

  def self.defalut_start_time
    t = Time.zone.now.advance(hours: 1)
    t - t.min * 60 - t.sec
  end

  # まだ出ていない番号を引く
  def lot_number
    ((1..75).to_a - numbers).sample
  end

  # まだビンゴしていないエントリーに対してビンゴしているかチェックする。
  # ビンゴしていたらエントリーのbingo_turnにターンをセットする。
  def check_bingo_for_entries!
    entries.includes(:card).where('entries.bingo_turn = 0').find_each do |entry|
      if entry.card.bingo?(numbers)
        entry.bingo_turn = numbers.length
        entry.save!
      end
    end
  end

  # 戻り値はハッシュ(key：ターン、value：userの配列)
  def bingo_users_for_each_turn
    users_for_each_turn = {}
    entries.includes(:user).where('entries.bingo_turn > 0').find_each do |entry|
      if users_for_each_turn[entry.bingo_turn]
        users_for_each_turn[entry.bingo_turn] << entry.user
      else
        users_for_each_turn[entry.bingo_turn] = [entry.user]
      end
    end
    users_for_each_turn
  end

  private

  def start_time_should_be_after_now
    errors.add(:start_time, 'は現在時刻以降を指定してください。') if start_time < Time.zone.now
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user

  before_action :set_game, only: %i[show create_number edit update destroy]

  def index
    @games = Game.all
  end

  # 抽選画面
  def show
    @entry_count = @game.entries.count
    @bingo_users_for_each_turn = @game.bingo_users_for_each_turn
  end

  # 抽選
  def create_number
    new_number = @game.lot_number

    return redirect_to [:admin, @game], notice: '全ての数が出ました。' unless new_number

    Game.transaction do
      @game.numbers << new_number
      @game.save!

      @game.check_bingo_for_entries!
    end

    @bingo_users_for_each_turn = @game.bingo_users_for_each_turn
  end

  def new
    @game = Game.new
    @game.name = Game.default_name
    @game.start_time = Game.defalut_start_time
  end

  def edit; end

  def create
    @game = Game.new(game_params)
    @game.numbers = []

    if @game.save
      redirect_to [:admin, @game], notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  def update
    if @game.update(game_params)
      redirect_to [:admin, @game], notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to admin_games_url, notice: 'Game was successfully destroyed.'
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :start_time)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
    return redirect_to(admin_games_url) if current_user&.admin?

    @games = Game.all
  end

  # play画面
  def show
    @game = Game.find(params[:id])

    # JavaScriptで使う
    @lot_numbers_json = @game.numbers.to_json

    card = current_user.entries.find_by(game_id: params[:id])&.card
    @numbers = card.numbers
    @bingo = card.bingo?(@game.numbers)
  end
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :game_name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :game_start_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ゲーム一覧</h1>

<table class="table table-bordered games-table">
  <thead>
    <tr>
      <th>名前</th>
      <th>開始時刻</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td width="220px"><%= l(game.start_time, format: :middle) %></td>
        <td width="100px"><%= link_to '参加する', new_game_entry_path(game), {:class => 'btn btn-default'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="game-title"><%= @game.name %></h1>

<div class="game-start-time text-center">
  <%= l(@game.start_time, format: :middle) %> 開始
</div>
<br>
<% if @bingo %>
  <%= image_tag 'bingo.png', class: 'bingo-img center-block' %>
  <div class="bingo-message text-center">当選おめでとうございます！</div>
<% else %>
  <div class="last-number">
    <%= @game.numbers.last %>
  </div>
<% end %>

<table class="card-table center-block">
  <thead>
    <tr>
      <th>B</th>
      <th>I</th>
      <th>N</th>
      <th>G</th>
      <th>O</th>
    </tr>
  </thead>

  <tbody>
    <% @numbers.each do |row| %>
      <tr>
        <% row.each do |number| %>
          <td data-number="<%= number %>">
            <% if number == 0 %>
              <%= image_tag 'free.png' %>
            <% else %>
              <%= number %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <div class="text-center">抽選番号の履歴</div>
  <div class="lot-numbers"><%= @game.numbers.join(', ') %></div>
</p>

<%= link_to 'ゲーム一覧へ', games_path, class: 'btn btn-link center-block' %>
<br>

<input id="lot_numbers_json" type="hidden" value=<%= @lot_numbers_json %> />
<script type="text/javascript">
  $(function(){
    App.notifications = App.cable.subscriptions.create(
      {  
        channel: "NotificationsChannel", 
        game_id: <%= @game.id %>
      },
      {
        received: function(data) {
          location.reload();
        }
      }
    );

    // ヒットしている番号の印表示。
    var lot_numbers_json = $('#lot_numbers_json').val();
    var lot_numbers = JSON.parse(lot_numbers_json);

    $('.card-table tr td').each(function(index, elm){
      var number = $(elm).data('number');
      if (lot_numbers.indexOf(number) >= 0 || number == 0) {
        $(elm).addClass('hit');
      }
    })
  });
</script>